image: k33g/wasm-university-sunny-tech-2022:0.0.0

tasks:
  - name: initialize
    before: |

      # ------------------------------------
      # wasmer
      # ------------------------------------
      source /home/gitpod/.wasmer/wasmer.sh
      wasmer --version
      # ------------------------------------
      # wasmtime
      # ------------------------------------
      wasmtime --version
      # ------------------------------------
      # wasmedge dependencies
      # ------------------------------------
      source /home/gitpod/.wasmedge/env
      wasmedge --version

    init: |
      echo "🚀 initialize"
      npm install
      clear
      export DOTNET_ROOT=$HOME/dotnet
      export PATH=$PATH:$HOME/dotnet
      #dotnet workload install wasm-tools
      #dotnet add package Wasi.Sdk --prerelease
      dotnet --version

  - name: 00-c-web
    command: |
      cd 00-c-web
      clear
      bat TODO.md

  - name: 01-go-hello
    command: |
      cd 01-go-hello
      clear
      bat TODO.md

  - name: 02-js-boids
    command: |
      cd 02-js-boids
      clear
      bat TODO.md

  - name: 02-wasm-go-boids
    command: |
      cd 02-wasm-go-boids
      clear
      bat TODO.md

  - name: 03-nodejs-rust-function
    command: |
      cd 03-nodejs-rust-function
      clear

  - name: 04-use-cli-grain-division
    command: |
      cd 04-use-cli-grain-division
      clear

  - name: 05-go-sat
    command: |
      cd 05-go-sat
      clear

  - name: 06-wasi-asp-dotnet
    command: |
      cd 06-wasi-asp-dotnet
      clear

  - name: 07-sat
    command: |
      cd 07-sat
      clear


ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public

vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - rust-lang.rust
    - bungcip.better-toml
    - aaron-bond.better-comments
    - grain-lang.vscode-grain
    - ms-dotnettools.vscode-dotnet-runtime
